--------------------------------------------------------
-- Archivo creado  - domingo-octubre-08-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADDRESS
--------------------------------------------------------

  CREATE TABLE "ODS"."ADDRESS" 
   (	"ADDRESSID" NUMBER, 
	"ADDRESSLINE1" VARCHAR2(2000 BYTE), 
	"ADDRESSLINE2" VARCHAR2(2000 BYTE), 
	"CITY" VARCHAR2(2000 BYTE), 
	"STATEPROVINCEID" NUMBER, 
	"POSTALCODE" NUMBER, 
	"SPATIALLOCATION" VARCHAR2(2000 BYTE), 
	"ROWGUID" VARCHAR2(2000 BYTE), 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BUSINESSENTITY
--------------------------------------------------------

  CREATE TABLE "ODS"."BUSINESSENTITY" 
   (	"BUSINESSENTITYID" NUMBER, 
	"ROWGUID" VARCHAR2(2000 BYTE), 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BUSINESSENTITYADDRESS
--------------------------------------------------------

  CREATE TABLE "ODS"."BUSINESSENTITYADDRESS" 
   (	"BUSINESSENTITYID" NUMBER, 
	"ADDRESSID" NUMBER, 
	"ADDRESSTYPEID" NUMBER, 
	"ROWGUID" VARCHAR2(2000 BYTE), 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COUNTRYREGION
--------------------------------------------------------

  CREATE TABLE "ODS"."COUNTRYREGION" 
   (	"COUNTRYREGIONCODE" VARCHAR2(2000 BYTE), 
	"NAME" VARCHAR2(2000 BYTE), 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPARTMENT
--------------------------------------------------------

  CREATE TABLE "ODS"."DEPARTMENT" 
   (	"DEPARTMENTID" NUMBER, 
	"NAME" VARCHAR2(2000 BYTE), 
	"GROUPNAME" VARCHAR2(2000 BYTE), 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMAILADDRESS
--------------------------------------------------------

  CREATE TABLE "ODS"."EMAILADDRESS" 
   (	"BUSINESSENTITYID" NUMBER, 
	"EMAILADDRESSID" NUMBER, 
	"EMAILADDRESS" VARCHAR2(2000 BYTE), 
	"ROWGUID" VARCHAR2(2000 BYTE), 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "ODS"."EMPLOYEE" 
   (	"BUSINESSENTITYID" NUMBER, 
	"NATIONALIDNUMBER" NUMBER, 
	"LOGINID" VARCHAR2(2000 BYTE), 
	"ORGANIZATIONNODE" VARCHAR2(2000 BYTE), 
	"ORGANIZATIONLEVEL" VARCHAR2(2000 BYTE), 
	"JOBTITLE" VARCHAR2(2000 BYTE), 
	"BIRTHDATE" DATE, 
	"MARITALSTATUS" VARCHAR2(2000 BYTE), 
	"GENDER" VARCHAR2(2000 BYTE), 
	"HIREDATE" DATE, 
	"SALARIEDFLAG" NUMBER, 
	"VACATIONHOURS" NUMBER, 
	"SICKLEAVEHOURS" NUMBER, 
	"CURRENTFLAG" NUMBER, 
	"ROWGUID" VARCHAR2(2000 BYTE), 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEEDEPARTMENTHISTORY
--------------------------------------------------------

  CREATE TABLE "ODS"."EMPLOYEEDEPARTMENTHISTORY" 
   (	"BUSINESSENTITYID" NUMBER, 
	"DEPARTMENTID" NUMBER, 
	"SHIFTID" NUMBER, 
	"STARTDATE" DATE, 
	"ENDDATE" VARCHAR2(2000 BYTE), 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEEPAYHISTORY
--------------------------------------------------------

  CREATE TABLE "ODS"."EMPLOYEEPAYHISTORY" 
   (	"BUSINESSENTITYID" NUMBER, 
	"RATECHANGEDATE" DATE, 
	"RATE" NUMBER, 
	"PAYFREQUENCY" NUMBER, 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERSON
--------------------------------------------------------

  CREATE TABLE "ODS"."PERSON" 
   (	"ROWGUID" VARCHAR2(2000 BYTE), 
	"TITLE" VARCHAR2(2000 BYTE), 
	"SUFFIX" VARCHAR2(2000 BYTE), 
	"PERSONTYPE" VARCHAR2(2000 BYTE), 
	"NAMESTYLE" NUMBER, 
	"MODIFIEDDATE" DATE, 
	"MIDDLENAME" VARCHAR2(2000 BYTE), 
	"LASTNAME" VARCHAR2(2000 BYTE), 
	"FIRSTNAME" VARCHAR2(2000 BYTE), 
	"EMAILPROMOTION" NUMBER, 
	"DEMOGRAPHICS" VARCHAR2(2000 BYTE), 
	"BUSINESSENTITYID" NUMBER, 
	"ADDITIONALCONTACTINFO" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERSONPHONE
--------------------------------------------------------

  CREATE TABLE "ODS"."PERSONPHONE" 
   (	"BUSINESSENTITYID" NUMBER, 
	"PHONENUMBER" VARCHAR2(2000 BYTE), 
	"PHONENUMBERTYPEID" NUMBER, 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "ODS"."PRODUCT" 
   (	"PRODUCTID" NUMBER, 
	"NAME" VARCHAR2(2000 BYTE), 
	"PRODUCTNUMBER" VARCHAR2(2000 BYTE), 
	"MAKEFLAG" NUMBER, 
	"FINISHEDGOODSFLAG" NUMBER, 
	"COLOR" VARCHAR2(2000 BYTE), 
	"SAFETYSTOCKLEVEL" NUMBER, 
	"REORDERPOINT" NUMBER, 
	"STANDARDCOST" NUMBER, 
	"LISTPRICE" NUMBER, 
	"PRODUCTSIZE" VARCHAR2(2000 BYTE), 
	"SIZEUNITMEASURECODE" VARCHAR2(2000 BYTE), 
	"WEIGHTUNITMEASURECODE" VARCHAR2(2000 BYTE), 
	"WEIGHT" VARCHAR2(2000 BYTE), 
	"DAYSTOMANUFACTURE" NUMBER, 
	"PRODUCTLINE" VARCHAR2(2000 BYTE), 
	"CLASS" VARCHAR2(2000 BYTE), 
	"STYLE" VARCHAR2(2000 BYTE), 
	"PRODUCTSUBCATEGORYID" VARCHAR2(2000 BYTE), 
	"PRODUCTMODELID" VARCHAR2(2000 BYTE), 
	"SELLSTARTDATE" DATE, 
	"SELLENDDATE" VARCHAR2(2000 BYTE), 
	"DISCONTINUEDDATE" VARCHAR2(2000 BYTE), 
	"ROWGUID" VARCHAR2(2000 BYTE), 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTCATEGORY
--------------------------------------------------------

  CREATE TABLE "ODS"."PRODUCTCATEGORY" 
   (	"PRODUCTCATEGORYID" NUMBER, 
	"NAME" VARCHAR2(2000 BYTE), 
	"ROWGUID" VARCHAR2(2000 BYTE), 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTSUBCATEGORY
--------------------------------------------------------

  CREATE TABLE "ODS"."PRODUCTSUBCATEGORY" 
   (	"PRODUCTSUBCATEGORYID" NUMBER, 
	"PRODUCTCATEGORYID" NUMBER, 
	"NAME" VARCHAR2(2000 BYTE), 
	"ROWGUID" VARCHAR2(2000 BYTE), 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STATEPROVINCE
--------------------------------------------------------

  CREATE TABLE "ODS"."STATEPROVINCE" 
   (	"STATEPROVINCEID" NUMBER, 
	"STATEPROVINCECODE" VARCHAR2(2000 BYTE), 
	"COUNTRYREGIONCODE" VARCHAR2(2000 BYTE), 
	"ISONLYSTATEPROVINCEFLAG" NUMBER, 
	"NAME" VARCHAR2(2000 BYTE), 
	"TERRITORYID" NUMBER, 
	"ROWGUID" VARCHAR2(2000 BYTE), 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ODS.ADDRESS
SET DEFINE OFF;
REM INSERTING into ODS.BUSINESSENTITY
SET DEFINE OFF;
REM INSERTING into ODS.BUSINESSENTITYADDRESS
SET DEFINE OFF;
REM INSERTING into ODS.COUNTRYREGION
SET DEFINE OFF;
REM INSERTING into ODS.DEPARTMENT
SET DEFINE OFF;
REM INSERTING into ODS.EMAILADDRESS
SET DEFINE OFF;
REM INSERTING into ODS.EMPLOYEE
SET DEFINE OFF;
REM INSERTING into ODS.EMPLOYEEDEPARTMENTHISTORY
SET DEFINE OFF;
REM INSERTING into ODS.EMPLOYEEPAYHISTORY
SET DEFINE OFF;
REM INSERTING into ODS.PERSON
SET DEFINE OFF;
REM INSERTING into ODS.PERSONPHONE
SET DEFINE OFF;
REM INSERTING into ODS.PRODUCT
SET DEFINE OFF;
REM INSERTING into ODS.PRODUCTCATEGORY
SET DEFINE OFF;
REM INSERTING into ODS.PRODUCTSUBCATEGORY
SET DEFINE OFF;
REM INSERTING into ODS.STATEPROVINCE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index IDX_BUSINESSENTITY_LOOKUP
--------------------------------------------------------

  CREATE INDEX "ODS"."IDX_BUSINESSENTITY_LOOKUP" ON "ODS"."BUSINESSENTITY" ("BUSINESSENTITYID", "ROWGUID", "MODIFIEDDATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
