--------------------------------------------------------
-- Archivo creado  - lunes-octubre-09-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADDRESS
--------------------------------------------------------

  CREATE TABLE "ODS"."ADDRESS" 
   (	"ADDRESSID" NUMBER, 
	"ADDRESSLINE1" VARCHAR2(2000 BYTE), 
	"ADDRESSLINE2" VARCHAR2(2000 BYTE), 
	"CITY" VARCHAR2(2000 BYTE), 
	"STATEPROVINCEID" NUMBER, 
	"POSTALCODE" NUMBER, 
	"SPATIALLOCATION" VARCHAR2(2000 BYTE), 
	"ROWGUID" VARCHAR2(2000 BYTE), 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BUSINESSENTITY
--------------------------------------------------------

  CREATE TABLE "ODS"."BUSINESSENTITY" 
   (	"BUSINESSENTITYID" NUMBER, 
	"ROWGUID" VARCHAR2(2000 BYTE), 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BUSINESSENTITYADDRESS
--------------------------------------------------------

  CREATE TABLE "ODS"."BUSINESSENTITYADDRESS" 
   (	"BUSINESSENTITYID" NUMBER, 
	"ADDRESSID" NUMBER, 
	"ADDRESSTYPEID" NUMBER, 
	"ROWGUID" VARCHAR2(2000 BYTE), 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COUNTRYREGION
--------------------------------------------------------

  CREATE TABLE "ODS"."COUNTRYREGION" 
   (	"COUNTRYREGIONCODE" VARCHAR2(2000 BYTE), 
	"NAME" VARCHAR2(2000 BYTE), 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPARTMENT
--------------------------------------------------------

  CREATE TABLE "ODS"."DEPARTMENT" 
   (	"DEPARTMENTID" NUMBER, 
	"NAME" VARCHAR2(2000 BYTE), 
	"GROUPNAME" VARCHAR2(2000 BYTE), 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMAILADDRESS
--------------------------------------------------------

  CREATE TABLE "ODS"."EMAILADDRESS" 
   (	"BUSINESSENTITYID" NUMBER, 
	"EMAILADDRESSID" NUMBER, 
	"EMAILADDRESS" VARCHAR2(2000 BYTE), 
	"ROWGUID" VARCHAR2(2000 BYTE), 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "ODS"."EMPLOYEE" 
   (	"BUSINESSENTITYID" NUMBER, 
	"NATIONALIDNUMBER" NUMBER, 
	"LOGINID" VARCHAR2(2000 BYTE), 
	"ORGANIZATIONNODE" VARCHAR2(2000 BYTE), 
	"ORGANIZATIONLEVEL" VARCHAR2(2000 BYTE), 
	"JOBTITLE" VARCHAR2(2000 BYTE), 
	"BIRTHDATE" DATE, 
	"MARITALSTATUS" VARCHAR2(2000 BYTE), 
	"GENDER" VARCHAR2(2000 BYTE), 
	"HIREDATE" DATE, 
	"SALARIEDFLAG" NUMBER, 
	"VACATIONHOURS" NUMBER, 
	"SICKLEAVEHOURS" NUMBER, 
	"CURRENTFLAG" NUMBER, 
	"ROWGUID" VARCHAR2(2000 BYTE), 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEEDEPARTMENTHISTORY
--------------------------------------------------------

  CREATE TABLE "ODS"."EMPLOYEEDEPARTMENTHISTORY" 
   (	"BUSINESSENTITYID" NUMBER, 
	"DEPARTMENTID" NUMBER, 
	"SHIFTID" NUMBER, 
	"STARTDATE" DATE, 
	"ENDDATE" VARCHAR2(2000 BYTE), 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEEPAYHISTORY
--------------------------------------------------------

  CREATE TABLE "ODS"."EMPLOYEEPAYHISTORY" 
   (	"BUSINESSENTITYID" NUMBER, 
	"RATECHANGEDATE" DATE, 
	"RATE" NUMBER, 
	"PAYFREQUENCY" NUMBER, 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERSON
--------------------------------------------------------

  CREATE TABLE "ODS"."PERSON" 
   (	"ROWGUID" VARCHAR2(2000 BYTE), 
	"TITLE" VARCHAR2(2000 BYTE), 
	"SUFFIX" VARCHAR2(2000 BYTE), 
	"PERSONTYPE" VARCHAR2(2000 BYTE), 
	"NAMESTYLE" NUMBER, 
	"MODIFIEDDATE" DATE, 
	"MIDDLENAME" VARCHAR2(2000 BYTE), 
	"LASTNAME" VARCHAR2(2000 BYTE), 
	"FIRSTNAME" VARCHAR2(2000 BYTE), 
	"EMAILPROMOTION" NUMBER, 
	"DEMOGRAPHICS" VARCHAR2(2000 BYTE), 
	"BUSINESSENTITYID" NUMBER, 
	"ADDITIONALCONTACTINFO" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERSONPHONE
--------------------------------------------------------

  CREATE TABLE "ODS"."PERSONPHONE" 
   (	"BUSINESSENTITYID" NUMBER, 
	"PHONENUMBER" VARCHAR2(2000 BYTE), 
	"PHONENUMBERTYPEID" NUMBER, 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "ODS"."PRODUCT" 
   (	"PRODUCTID" NUMBER, 
	"NAME" VARCHAR2(2000 BYTE), 
	"PRODUCTNUMBER" VARCHAR2(2000 BYTE), 
	"MAKEFLAG" NUMBER, 
	"FINISHEDGOODSFLAG" NUMBER, 
	"COLOR" VARCHAR2(2000 BYTE), 
	"SAFETYSTOCKLEVEL" NUMBER, 
	"REORDERPOINT" NUMBER, 
	"STANDARDCOST" NUMBER, 
	"LISTPRICE" NUMBER, 
	"PRODUCTSIZE" VARCHAR2(2000 BYTE), 
	"SIZEUNITMEASURECODE" VARCHAR2(2000 BYTE), 
	"WEIGHTUNITMEASURECODE" VARCHAR2(2000 BYTE), 
	"WEIGHT" VARCHAR2(2000 BYTE), 
	"DAYSTOMANUFACTURE" NUMBER, 
	"PRODUCTLINE" VARCHAR2(2000 BYTE), 
	"CLASS" VARCHAR2(2000 BYTE), 
	"STYLE" VARCHAR2(2000 BYTE), 
	"PRODUCTSUBCATEGORYID" VARCHAR2(2000 BYTE), 
	"PRODUCTMODELID" VARCHAR2(2000 BYTE), 
	"SELLSTARTDATE" DATE, 
	"SELLENDDATE" VARCHAR2(2000 BYTE), 
	"DISCONTINUEDDATE" VARCHAR2(2000 BYTE), 
	"ROWGUID" VARCHAR2(2000 BYTE), 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTCATEGORY
--------------------------------------------------------

  CREATE TABLE "ODS"."PRODUCTCATEGORY" 
   (	"PRODUCTCATEGORYID" NUMBER, 
	"NAME" VARCHAR2(2000 BYTE), 
	"ROWGUID" VARCHAR2(2000 BYTE), 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTSUBCATEGORY
--------------------------------------------------------

  CREATE TABLE "ODS"."PRODUCTSUBCATEGORY" 
   (	"PRODUCTSUBCATEGORYID" NUMBER, 
	"PRODUCTCATEGORYID" NUMBER, 
	"NAME" VARCHAR2(2000 BYTE), 
	"ROWGUID" VARCHAR2(2000 BYTE), 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STATEPROVINCE
--------------------------------------------------------

  CREATE TABLE "ODS"."STATEPROVINCE" 
   (	"STATEPROVINCEID" NUMBER, 
	"STATEPROVINCECODE" VARCHAR2(2000 BYTE), 
	"COUNTRYREGIONCODE" VARCHAR2(2000 BYTE), 
	"ISONLYSTATEPROVINCEFLAG" NUMBER, 
	"NAME" VARCHAR2(2000 BYTE), 
	"TERRITORYID" NUMBER, 
	"ROWGUID" VARCHAR2(2000 BYTE), 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ODS.ADDRESS
SET DEFINE OFF;
REM INSERTING into ODS.BUSINESSENTITY
SET DEFINE OFF;
REM INSERTING into ODS.BUSINESSENTITYADDRESS
SET DEFINE OFF;
REM INSERTING into ODS.COUNTRYREGION
SET DEFINE OFF;
REM INSERTING into ODS.DEPARTMENT
SET DEFINE OFF;
REM INSERTING into ODS.EMAILADDRESS
SET DEFINE OFF;
REM INSERTING into ODS.EMPLOYEE
SET DEFINE OFF;
REM INSERTING into ODS.EMPLOYEEDEPARTMENTHISTORY
SET DEFINE OFF;
REM INSERTING into ODS.EMPLOYEEPAYHISTORY
SET DEFINE OFF;
REM INSERTING into ODS.PERSON
SET DEFINE OFF;
REM INSERTING into ODS.PERSONPHONE
SET DEFINE OFF;
REM INSERTING into ODS.PRODUCT
SET DEFINE OFF;
REM INSERTING into ODS.PRODUCTCATEGORY
SET DEFINE OFF;
REM INSERTING into ODS.PRODUCTSUBCATEGORY
SET DEFINE OFF;
REM INSERTING into ODS.STATEPROVINCE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ADDRESS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ODS"."ADDRESS_PK" ON "ODS"."ADDRESS" ("ADDRESSID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_BUSINESSENTITY_LOOKUP
--------------------------------------------------------

  CREATE INDEX "ODS"."IDX_BUSINESSENTITY_LOOKUP" ON "ODS"."BUSINESSENTITY" ("BUSINESSENTITYID", "ROWGUID", "MODIFIEDDATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DEPARTMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ODS"."DEPARTMENT_PK" ON "ODS"."DEPARTMENT" ("DEPARTMENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EMAILADDRESS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ODS"."EMAILADDRESS_PK" ON "ODS"."EMAILADDRESS" ("BUSINESSENTITYID", "EMAILADDRESS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ODS"."EMPLOYEE_PK" ON "ODS"."EMPLOYEE" ("BUSINESSENTITYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEEDEPARTMENTHISTORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ODS"."EMPLOYEEDEPARTMENTHISTORY_PK" ON "ODS"."EMPLOYEEDEPARTMENTHISTORY" ("BUSINESSENTITYID", "DEPARTMENTID", "STARTDATE", "SHIFTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEEPAYHISTORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ODS"."EMPLOYEEPAYHISTORY_PK" ON "ODS"."EMPLOYEEPAYHISTORY" ("BUSINESSENTITYID", "RATECHANGEDATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PERSON_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ODS"."PERSON_PK" ON "ODS"."PERSON" ("BUSINESSENTITYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PERSONPHONE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ODS"."PERSONPHONE_PK" ON "ODS"."PERSONPHONE" ("BUSINESSENTITYID", "PHONENUMBER", "PHONENUMBERTYPEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRODUCT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ODS"."PRODUCT_PK" ON "ODS"."PRODUCT" ("PRODUCTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRODUCTCATEGORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ODS"."PRODUCTCATEGORY_PK" ON "ODS"."PRODUCTCATEGORY" ("PRODUCTCATEGORYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRODUCTSUBCATEGORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ODS"."PRODUCTSUBCATEGORY_PK" ON "ODS"."PRODUCTSUBCATEGORY" ("PRODUCTSUBCATEGORYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ADDRESS
--------------------------------------------------------

  ALTER TABLE "ODS"."ADDRESS" MODIFY ("ADDRESSID" NOT NULL ENABLE);
  ALTER TABLE "ODS"."ADDRESS" ADD CONSTRAINT "ADDRESS_PK" PRIMARY KEY ("ADDRESSID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BUSINESSENTITY
--------------------------------------------------------

  ALTER TABLE "ODS"."BUSINESSENTITY" ADD CONSTRAINT "BUSINESSENTITY_PK" PRIMARY KEY ("BUSINESSENTITYID") DISABLE;
--------------------------------------------------------
--  Constraints for Table BUSINESSENTITYADDRESS
--------------------------------------------------------

  ALTER TABLE "ODS"."BUSINESSENTITYADDRESS" MODIFY ("ADDRESSID" NOT NULL ENABLE);
  ALTER TABLE "ODS"."BUSINESSENTITYADDRESS" ADD CONSTRAINT "BUSINESSENTITYADDRESS_PK" PRIMARY KEY ("ADDRESSID", "BUSINESSENTITYID") DISABLE;
--------------------------------------------------------
--  Constraints for Table COUNTRYREGION
--------------------------------------------------------

  ALTER TABLE "ODS"."COUNTRYREGION" MODIFY ("COUNTRYREGIONCODE" NOT NULL ENABLE);
  ALTER TABLE "ODS"."COUNTRYREGION" ADD CONSTRAINT "COUNTRYREGION_PK" PRIMARY KEY ("COUNTRYREGIONCODE") DISABLE;
--------------------------------------------------------
--  Constraints for Table DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "ODS"."DEPARTMENT" MODIFY ("DEPARTMENTID" NOT NULL ENABLE);
  ALTER TABLE "ODS"."DEPARTMENT" ADD CONSTRAINT "DEPARTMENT_PK" PRIMARY KEY ("DEPARTMENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMAILADDRESS
--------------------------------------------------------

  ALTER TABLE "ODS"."EMAILADDRESS" MODIFY ("BUSINESSENTITYID" NOT NULL ENABLE);
  ALTER TABLE "ODS"."EMAILADDRESS" MODIFY ("EMAILADDRESS" NOT NULL ENABLE);
  ALTER TABLE "ODS"."EMAILADDRESS" ADD CONSTRAINT "EMAILADDRESS_PK" PRIMARY KEY ("BUSINESSENTITYID", "EMAILADDRESS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "ODS"."EMPLOYEE" MODIFY ("BUSINESSENTITYID" NOT NULL ENABLE);
  ALTER TABLE "ODS"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("BUSINESSENTITYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEEDEPARTMENTHISTORY
--------------------------------------------------------

  ALTER TABLE "ODS"."EMPLOYEEDEPARTMENTHISTORY" MODIFY ("BUSINESSENTITYID" NOT NULL ENABLE);
  ALTER TABLE "ODS"."EMPLOYEEDEPARTMENTHISTORY" MODIFY ("DEPARTMENTID" NOT NULL ENABLE);
  ALTER TABLE "ODS"."EMPLOYEEDEPARTMENTHISTORY" MODIFY ("SHIFTID" NOT NULL ENABLE);
  ALTER TABLE "ODS"."EMPLOYEEDEPARTMENTHISTORY" MODIFY ("STARTDATE" NOT NULL ENABLE);
  ALTER TABLE "ODS"."EMPLOYEEDEPARTMENTHISTORY" ADD CONSTRAINT "EMPLOYEEDEPARTMENTHISTORY_PK" PRIMARY KEY ("BUSINESSENTITYID", "DEPARTMENTID", "STARTDATE", "SHIFTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEEPAYHISTORY
--------------------------------------------------------

  ALTER TABLE "ODS"."EMPLOYEEPAYHISTORY" MODIFY ("BUSINESSENTITYID" NOT NULL ENABLE);
  ALTER TABLE "ODS"."EMPLOYEEPAYHISTORY" MODIFY ("RATECHANGEDATE" NOT NULL ENABLE);
  ALTER TABLE "ODS"."EMPLOYEEPAYHISTORY" ADD CONSTRAINT "EMPLOYEEPAYHISTORY_PK" PRIMARY KEY ("BUSINESSENTITYID", "RATECHANGEDATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PERSON
--------------------------------------------------------

  ALTER TABLE "ODS"."PERSON" MODIFY ("BUSINESSENTITYID" NOT NULL ENABLE);
  ALTER TABLE "ODS"."PERSON" ADD CONSTRAINT "PERSON_PK" PRIMARY KEY ("BUSINESSENTITYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PERSONPHONE
--------------------------------------------------------

  ALTER TABLE "ODS"."PERSONPHONE" MODIFY ("BUSINESSENTITYID" NOT NULL ENABLE);
  ALTER TABLE "ODS"."PERSONPHONE" MODIFY ("PHONENUMBER" NOT NULL ENABLE);
  ALTER TABLE "ODS"."PERSONPHONE" MODIFY ("PHONENUMBERTYPEID" NOT NULL ENABLE);
  ALTER TABLE "ODS"."PERSONPHONE" ADD CONSTRAINT "PERSONPHONE_PK" PRIMARY KEY ("BUSINESSENTITYID", "PHONENUMBER", "PHONENUMBERTYPEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "ODS"."PRODUCT" MODIFY ("PRODUCTID" NOT NULL ENABLE);
  ALTER TABLE "ODS"."PRODUCT" ADD CONSTRAINT "PRODUCT_PK" PRIMARY KEY ("PRODUCTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTCATEGORY
--------------------------------------------------------

  ALTER TABLE "ODS"."PRODUCTCATEGORY" MODIFY ("PRODUCTCATEGORYID" NOT NULL ENABLE);
  ALTER TABLE "ODS"."PRODUCTCATEGORY" ADD CONSTRAINT "PRODUCTCATEGORY_PK" PRIMARY KEY ("PRODUCTCATEGORYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTSUBCATEGORY
--------------------------------------------------------

  ALTER TABLE "ODS"."PRODUCTSUBCATEGORY" MODIFY ("PRODUCTSUBCATEGORYID" NOT NULL ENABLE);
  ALTER TABLE "ODS"."PRODUCTSUBCATEGORY" ADD CONSTRAINT "PRODUCTSUBCATEGORY_PK" PRIMARY KEY ("PRODUCTSUBCATEGORYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STATEPROVINCE
--------------------------------------------------------

  ALTER TABLE "ODS"."STATEPROVINCE" MODIFY ("STATEPROVINCEID" NOT NULL ENABLE);
  ALTER TABLE "ODS"."STATEPROVINCE" ADD CONSTRAINT "STATEPROVINCE_ID" PRIMARY KEY ("STATEPROVINCEID") DISABLE;
--------------------------------------------------------
--  Ref Constraints for Table ADDRESS
--------------------------------------------------------

  ALTER TABLE "ODS"."ADDRESS" ADD CONSTRAINT "ADDRESS_FK1" FOREIGN KEY ("STATEPROVINCEID")
	  REFERENCES "ODS"."STATEPROVINCE" ("STATEPROVINCEID") ON DELETE CASCADE DISABLE;
--------------------------------------------------------
--  Ref Constraints for Table BUSINESSENTITYADDRESS
--------------------------------------------------------

  ALTER TABLE "ODS"."BUSINESSENTITYADDRESS" ADD CONSTRAINT "BUSINESSENTITYADDRESS_FK1" FOREIGN KEY ("ADDRESSID")
	  REFERENCES "ODS"."ADDRESS" ("ADDRESSID") ON DELETE CASCADE DISABLE;
  ALTER TABLE "ODS"."BUSINESSENTITYADDRESS" ADD CONSTRAINT "BUSINESSENTITYADDRESS_FK2" FOREIGN KEY ("BUSINESSENTITYID")
	  REFERENCES "ODS"."BUSINESSENTITY" ("BUSINESSENTITYID") ON DELETE CASCADE DISABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMAILADDRESS
--------------------------------------------------------

  ALTER TABLE "ODS"."EMAILADDRESS" ADD CONSTRAINT "EMAILADDRESS_FK1" FOREIGN KEY ("BUSINESSENTITYID")
	  REFERENCES "ODS"."BUSINESSENTITY" ("BUSINESSENTITYID") ON DELETE CASCADE DISABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "ODS"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_FK1" FOREIGN KEY ("BUSINESSENTITYID")
	  REFERENCES "ODS"."BUSINESSENTITY" ("BUSINESSENTITYID") ON DELETE CASCADE DISABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYEEDEPARTMENTHISTORY
--------------------------------------------------------

  ALTER TABLE "ODS"."EMPLOYEEDEPARTMENTHISTORY" ADD CONSTRAINT "EMPLOYEEDEPARTMENTHISTORY_FK1" FOREIGN KEY ("BUSINESSENTITYID")
	  REFERENCES "ODS"."BUSINESSENTITY" ("BUSINESSENTITYID") ON DELETE CASCADE DISABLE;
  ALTER TABLE "ODS"."EMPLOYEEDEPARTMENTHISTORY" ADD CONSTRAINT "EMPLOYEEDEPARTMENTHISTORY_FK2" FOREIGN KEY ("DEPARTMENTID")
	  REFERENCES "ODS"."DEPARTMENT" ("DEPARTMENTID") ON DELETE CASCADE DISABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYEEPAYHISTORY
--------------------------------------------------------

  ALTER TABLE "ODS"."EMPLOYEEPAYHISTORY" ADD CONSTRAINT "EMPLOYEEPAYHISTORY_FK1" FOREIGN KEY ("BUSINESSENTITYID")
	  REFERENCES "ODS"."BUSINESSENTITY" ("BUSINESSENTITYID") ON DELETE CASCADE DISABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERSON
--------------------------------------------------------

  ALTER TABLE "ODS"."PERSON" ADD CONSTRAINT "PERSON_FK1" FOREIGN KEY ("BUSINESSENTITYID")
	  REFERENCES "ODS"."BUSINESSENTITY" ("BUSINESSENTITYID") ON DELETE CASCADE DISABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERSONPHONE
--------------------------------------------------------

  ALTER TABLE "ODS"."PERSONPHONE" ADD CONSTRAINT "PERSONPHONE_FK1" FOREIGN KEY ("BUSINESSENTITYID")
	  REFERENCES "ODS"."BUSINESSENTITY" ("BUSINESSENTITYID") ON DELETE CASCADE DISABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTSUBCATEGORY
--------------------------------------------------------

  ALTER TABLE "ODS"."PRODUCTSUBCATEGORY" ADD CONSTRAINT "PRODUCTSUBCATEGORY_FK1" FOREIGN KEY ("PRODUCTCATEGORYID")
	  REFERENCES "ODS"."PRODUCTCATEGORY" ("PRODUCTCATEGORYID") ON DELETE CASCADE DISABLE;
