--------------------------------------------------------
-- Archivo creado  - domingo-octubre-08-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PARAMETROS
--------------------------------------------------------

  CREATE TABLE "ETL_USER"."PARAMETROS" 
   (	"SISTEMA" VARCHAR2(100 BYTE), 
	"NOMBRE_PARAM" VARCHAR2(20 BYTE), 
	"VALOR_PARAM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ETL_USER.PARAMETROS
SET DEFINE OFF;
Insert into ETL_USER.PARAMETROS (SISTEMA,NOMBRE_PARAM,VALOR_PARAM) values ('TAREA_1','HOSTNAME','192.168.199.129');
Insert into ETL_USER.PARAMETROS (SISTEMA,NOMBRE_PARAM,VALOR_PARAM) values ('TAREA_1','DATEBASENAME','xe');
Insert into ETL_USER.PARAMETROS (SISTEMA,NOMBRE_PARAM,VALOR_PARAM) values ('TAREA_1','PORTNUMBER','1521');
Insert into ETL_USER.PARAMETROS (SISTEMA,NOMBRE_PARAM,VALOR_PARAM) values ('TAREA_1','USERNAME','ETL_USER');
Insert into ETL_USER.PARAMETROS (SISTEMA,NOMBRE_PARAM,VALOR_PARAM) values ('TAREA_1','SCHEMA','ODS');
Insert into ETL_USER.PARAMETROS (SISTEMA,NOMBRE_PARAM,VALOR_PARAM) values ('TAREA_1','DIR_FILE','C:\WAITS\TAREA1');
Insert into ETL_USER.PARAMETROS (SISTEMA,NOMBRE_PARAM,VALOR_PARAM) values ('TAREA_1','PASSWORD','1234');
Insert into ETL_USER.PARAMETROS (SISTEMA,NOMBRE_PARAM,VALOR_PARAM) values ('TAREA_1','SCHEMA_DW','DATA_WAREHOUSE');
